version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis

  celery_demo:
    build: ./
    container_name: celery_demo
    ports:
      - "8001:8000"
    command: ["/opt/venv/bin/python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./:/celery_demo
    env_file:
      - ./env/django.env
    stdin_open: true
    tty: true
    depends_on:
      - redis

  celery_worker_default:
    build: ./
    container_name: celery_worker_default
    command: celery --app=celery_demo worker -l INFO -Q default
    volumes:
      - ./:/celery_demo
    env_file:
      - ./env/django.env
    depends_on:
      - redis

  celery_worker_beat:
    build: ./
    container_name: celery_worker_beat_tasks
    command: celery --app=celery_demo worker -l INFO -Q beat_tasks
    volumes:
      - ./:/celery_demo
    env_file:
      - ./env/django.env
    depends_on:
      - redis

  celery_beat:
    build: ./
    container_name: celery_beat
    command: celery --app=celery_demo beat -l INFO
    volumes:
      - ./:/celery_demo
    env_file:
      - ./env/django.env
    depends_on:
      - redis
      - celery_worker_beat